export const INITIALISE_BOOKSHELF_START = "INITALISE_BOOKSHELF_START";
export const INITIALISE_BOOKSHELF_SUCCESS = "INITIALISE_BOOKSHELF_SUCCESS";
export const INITIALISE_BOOKSHELF_FAIL = "INITIALISE_BOOKSHELF_FAIL";

/*
export const ADD_BOOK_START = "ADD_BOOK_START";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_FAIL = "ADD_BOOK_FAIL";

export const TOGGLE_READ_START = "TOGGLE_READ_START";
export const TOGGLE_READ_SUCCESS = "TOGGLE_READ_SUCCESS";
export const TOGGLE_READ_FAIL = "TOGGLE_READ_FAIL";

export const DELETE_BOOK_START = "DELETE_BOOK_START";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_FAIL = "DELETE_BOOK_FAIL";
*/
