export const INITIALISE_BOOKSHELF_START = "INITALISE_BOOKSHELF_START";
export const INITIALISE_BOOKSHELF_SUCCESS = "INITIALISE_BOOKSHELF_SUCCESS";
export const INITIALISE_BOOKSHELF_FAIL = "INITIALISE_BOOKSHELF_FAIL";
